# Generated by Django 4.1 on 2022-08-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitment",
            name="country",
            field=models.CharField(default="한국", max_length=128, verbose_name="국가"),
        ),
        migrations.AddField(
            model_name="recruitment",
            name="region",
            field=models.CharField(default="서울", max_length=128, verbose_name="지역"),
        ),
    ]
