# Generated by Django 4.0.6 on 2022-08-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='corporation',
            name='region',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='country',
            field=models.CharField(default='한국', max_length=128, verbose_name='국가'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='region',
            field=models.CharField(default='서울', max_length=128, verbose_name='지역'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
